#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue May 19 16:28:22 HKT 2026
maven-metadata-codemc-repo.xml.error=
maven-metadata-codemc-repo.xml.lastUpdated=1779179302234
maven-metadata-jitpack.xml.error=
maven-metadata-jitpack.xml.lastUpdated=1779179302233
maven-metadata-papermc.xml.lastUpdated=1779179302230
maven-metadata-plugilyprojects-snapshots.xml.error=
maven-metadata-plugilyprojects-snapshots.xml.lastUpdated=1779179302233
maven-metadata-plugilyprojects.xml.error=
maven-metadata-plugilyprojects.xml.lastUpdated=1779179302232
maven-metadata-spigot-repo.xml.error=
maven-metadata-spigot-repo.xml.lastUpdated=1779179302229
